"""initial evidence table

Revision ID: 3e0154a557ec
Revises: 
Create Date: 2026-04-12 09:32:07.304921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e0154a557ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('sdg', sa.String(length=100), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('priority_area', sa.String(length=200), nullable=True),
    sa.Column('sub_area', sa.String(length=200), nullable=True),
    sa.Column('doi', sa.String(length=300), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(abstract, '') || ' ' || coalesce(authors, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index('ix_evidence_search_vector', 'evidence', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('evidence_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(text, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_chunks_evidence_id'), 'evidence_chunks', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_chunks_id'), 'evidence_chunks', ['id'], unique=False)
    op.create_index('ix_evidence_chunks_search_vector', 'evidence_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_chunks_search_vector', table_name='evidence_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_evidence_chunks_id'), table_name='evidence_chunks')
    op.drop_index(op.f('ix_evidence_chunks_evidence_id'), table_name='evidence_chunks')
    op.drop_table('evidence_chunks')
    op.drop_index('ix_evidence_search_vector', table_name='evidence', postgresql_using='gin')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
